Repository TeamPINGLE/PINGLE-iOS, pull requests merged in 2024-01, with the labels that each got.

#4 Feat [#3] TabBarViewController UI 및 기능 구현
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Literals/ImageLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgAddPingle.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgAddPingle.imageset/Huge-icon-2.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgAddPingle.imageset/Huge-icon@2x-2.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgAddPingle.imageset/Huge-icon@3x-2.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgAddPingleSelected.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgAddPingleSelected.imageset/Huge-icon-3.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgAddPingleSelected.imageset/Huge-icon@2x-3.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgAddPingleSelected.imageset/Huge-icon@3x-3.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgHome.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgHome.imageset/Huge-icon-1.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgHome.imageset/Huge-icon@2x-1.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgHome.imageset/Huge-icon@3x-1.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgHomeSelected.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgHomeSelected.imageset/Huge-icon.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgHomeSelected.imageset/Huge-icon@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgHomeSelected.imageset/Huge-icon@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgSetting.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgSetting.imageset/Huge-icon-4.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgSetting.imageset/Huge-icon@2x-4.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgSetting.imageset/Huge-icon@3x-4.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgSettingSelected.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgSettingSelected.imageset/Huge-icon-5.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgSettingSelected.imageset/Huge-icon@2x-5.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgSettingSelected.imageset/Huge-icon@3x-5.png
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/HomeMapViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/f.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/TabBar/PINGLETabBarController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/TabBar/TabBarItem.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/TabBar/e.swift
Labels: Feat, 채은

#7 Feat [#5] splash UI 구현
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Literals/ImageLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgApplelogo.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgApplelogo.imageset/applelogo.svg
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgApplelogo.imageset/applelogo@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgApplelogo.imageset/applelogo@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Info.plist
  PINGLE-iOS/PINGLE-iOS/PINGLE-iOS.entitlements
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/LoginViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/c.swift
Labels: Feat, 민수

#9 Feat [#8] OnboardingView UI 구현
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Extensions/UIButton+.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/ImageLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgSample.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgSample.imageset/—Pngtree—note book and pencil 3d_6861622 2.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgSample.imageset/—Pngtree—note book and pencil 3d_6861622 2@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgSample.imageset/—Pngtree—note book and pencil 3d_6861622 2@3x.png
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/LoginViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/OnboardingViewController.swift
Labels: Feat, 민수

#14 Feat [#10] 핑글 개최 안내 페이지 UI 구현
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Literals/ImageLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgExitButton.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgExitButton.imageset/all_ic_x.svg
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgExitButton.imageset/all_ic_x@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgExitButton.imageset/all_ic_x@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgMettingGraphic.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgMettingGraphic.imageset/graphic.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgMettingGraphic.imageset/graphic@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgMettingGraphic.imageset/graphic@3x.png
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/View/h.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/MakeMettingGuideViewController.swift
Labels: Feat, 민지

#16 Feat[#15] pingle category button 클래스 구현
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Components/PINGLECategoryButton.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/ImageLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ButtonCustomTest.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/SelectCategoryViewController.swift
Labels: Feat, 민지

#20 Feat [#12] Search organization UI 구현
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Extensions/CALayer+.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/ImageLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgArrowLeft.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgArrowLeft.imageset/all_ic_arrow_left.svg
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgArrowLeft.imageset/all_ic_arrow_left@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgArrowLeft.imageset/all_ic_arrow_left@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgCheckDefault.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgCheckDefault.imageset/Status=all_check_default.svg
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgCheckDefault.imageset/Status=all_check_default@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgCheckDefault.imageset/Status=all_check_default@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgCheckSelected.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgCheckSelected.imageset/Status=all_check_selected.svg
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgCheckSelected.imageset/Status=all_check_selected@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgCheckSelected.imageset/Status=all_check_selected@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgSearchIcon.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgSearchIcon.imageset/all_ic_search.svg
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgSearchIcon.imageset/all_ic_search@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgSearchIcon.imageset/all_ic_search@3x.png
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/BasePaddingLabel.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/Cell/SearchCollectionViewCell.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/Model/SearchedModel.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/View/SearchOrganizationView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/View/d.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/OnboardingViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/SearchOrganizationViewController.swift
Labels: Feat, 민수

#24 Feat [#21] PINGLETextFieldView 구현
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Components/PINGLETextFieldView.swift
Labels: Feat, 민수

#26 Feat [#25] PINGLEWarningToastView 구현
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Components/PINGLEWarningToastView.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/ImageLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgWarningNotice.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgWarningNotice.imageset/ob_ic_notice.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgWarningNotice.imageset/ob_ic_notice@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgWarningNotice.imageset/ob_ic_notice@3x.png
Labels: Feat, 민수

#27 Feat[#17] category selection view
  PINGLE-iOS/PINGLE-iOS/Global/Literals/ImageLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icBackButton.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icBackButton.imageset/all_ic_arrow_left.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icBackButton.imageset/all_ic_arrow_left@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icBackButton.imageset/all_ic_arrow_left@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar1.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar1.imageset/plan_pgbar_1.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar1.imageset/plan_pgbar_1@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar1.imageset/plan_pgbar_1@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar2.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar2.imageset/plan_pgbar_2.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar2.imageset/plan_pgbar_2@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar2.imageset/plan_pgbar_2@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar3.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar3.imageset/plan_pgbar_3.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar3.imageset/plan_pgbar_3@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar3.imageset/plan_pgbar_3@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar4.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar4.imageset/plan_pgbar_4.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar4.imageset/plan_pgbar_4@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar4.imageset/plan_pgbar_4@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar5.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar5.imageset/plan_pgbar_5.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar5.imageset/plan_pgbar_5@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar5.imageset/plan_pgbar_5@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar6.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar6.imageset/plan_pgbar_6.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar6.imageset/plan_pgbar_6@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar6.imageset/plan_pgbar_6@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar7.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar7.imageset/plan_pgbar_7.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar7.imageset/plan_pgbar_7@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgProgressBar7.imageset/plan_pgbar_7@3x.png
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/Components/MeetingExitButton.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/MakeMettingGuideViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/SelectCategoryViewController.swift
Labels: Feat, 민지

#30 Feat[#28] metting introduction 뷰 구현
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/MeetingIntroductionViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/SelectCategoryViewController.swift
Labels: Feat, 민지

#31 Feat [#29] 기존 단체 입장 초대 코드 입력 뷰 UI 구현
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Extensions/UIView+.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/ImageLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icInfo.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icInfo.imageset/all_ic_info.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icInfo.imageset/all_ic_info@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icInfo.imageset/all_ic_info@3x.png
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/View/OrganizationInfoView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EnterInviteCodeViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/SearchOrganizationViewController.swift
Labels: Feat, 민수

#35 Feat [#32] 기존 단체 입장 완료 화면 구현
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/View/SearchOrganizationView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EnterInviteCodeViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EntranceCompletedViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/LoginViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/OnboardingViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/SearchOrganizationViewController.swift
Labels: Feat, 민수

#37 Feat[#34] date picker custom view UI 구현 및 테스트
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Font.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Info.plist
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ButtonCustomTest.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/View/CustomDatePickerView.swift
Labels: Feat, 민지

#40 Chore [#33] 중간 과제용 리드미 수정
  README.md
Labels: 채은, Chore

#39 Feat [#23] 홈 화면 디테일 UI 및 기능 구현
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Extensions/String+.swift
  PINGLE-iOS/PINGLE-iOS/Global/Extensions/UIButton+.swift
  PINGLE-iOS/PINGLE-iOS/Global/Extensions/UILabel+.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/ImageLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icCalendar.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icCalendar.imageset/all_ic_cal.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icCalendar.imageset/all_ic_cal@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icCalendar.imageset/all_ic_cal@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icLocation.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icLocation.imageset/all_ic_map.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icLocation.imageset/all_ic_map@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icLocation.imageset/all_ic_map@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgMultiBadge.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgMultiBadge.imageset/name=all_badge_multi.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgMultiBadge.imageset/name=all_badge_multi@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgMultiBadge.imageset/name=all_badge_multi@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgOthersBadge.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgOthersBadge.imageset/name=all_badge_others.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgOthersBadge.imageset/name=all_badge_others@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgOthersBadge.imageset/name=all_badge_others@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgPlayBadge.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgPlayBadge.imageset/name=all_badge_play.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgPlayBadge.imageset/name=all_badge_play@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgPlayBadge.imageset/name=all_badge_play@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgStudyBadge.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgStudyBadge.imageset/name=all_badge_study.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgStudyBadge.imageset/name=all_badge_study@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgStudyBadge.imageset/name=all_badge_study@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Font.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/Components/ChipButton.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/Components/PINGLEMarker.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/Model/HomePinDetailResponseDTO.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeDetailPopUpView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeMapDetailView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeMapView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeMapViewController.swift
Labels: Feat, 채은

#45 Feat [#36] 설정 화면 UI 구현
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Literals/ImageLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icArrowRight.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icArrowRight.imageset/all_ic_arrow_right.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icArrowRight.imageset/all_ic_arrow_right@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icArrowRight.imageset/all_ic_arrow_right@3x.png
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/Component/OrganizationButton.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/Component/SettingSelectButton.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/View/AccountPopUpView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/View/SettingSelectView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/ViewController/SettingViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/j.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/TabBar/PINGLETabBarController.swift
Labels: Feat, 민수

#49 Feat [#44] 홈 화면 리스트뷰 연결 및 공사중 뷰 연결
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeListViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeMapViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/TabBar/PINGLETabBarController.swift
Labels: Feat, 채은

#56 Feat[#55] 오픈 채팅방 링크 입력뷰 UI 구현
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/InsertOpenChatLinkViewController.swift
Labels: Feat, 민지

#52 Fix [#51] 로그인 온보딩 플로우 디자인 수정했습니다.
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Font.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/Cell/SearchCollectionViewCell.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/Component/BasePaddingLabel.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/View/OrganizationInfoView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/View/SearchOrganizationView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EnterInviteCodeViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EntranceCompletedViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/LoginViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/OnboardingViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/SearchOrganizationViewController.swift
Labels: Fix, 민수

#53 Feat[#47] place selection viewcontroller 구현
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/Cell/PlaceSelectionCollectionViewCell.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/Model/SearchedPlaceModel.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/View/SearchPlaceView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/DateSelectionViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/MakeMeetingGuideViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/MeetingIntroductionViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/PlaceSelectionViewController.swift
Labels: Feat, 민지

#57 Feat[#54] recruitment view 구현
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/Components/RecruitButton.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/RecruitmentViewController.swift
Labels: Feat, 민지

#61 Setting [#60] 네트워크 서버 통신 기초 세팅
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PINGLE-iOS/PINGLE-iOS/Network/Base/APIEventLogger.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/APIRequestLoader.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/BaseResponse.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/HTTPHeaderFieldKey.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/KeychainHandler.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/NetworkResult.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/NetworkService.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/TargetType.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/k.swift
  PINGLE-iOS/PINGLE-iOS/Network/Home/DTO/Request/HomePinListRequestQueryDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/Home/DTO/Response/HomePinDetailResponseDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/Home/DTO/Response/HomePinListResponseDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/Home/Router/HomeTarget.swift
  PINGLE-iOS/PINGLE-iOS/Network/Home/Service/HomeService.swift
  PINGLE-iOS/PINGLE-iOS/Network/Home/o.swift
Labels: Network, Setting, 채은

#65 Network [#62] 핀 목록 API 연결 및 Data Bind
  PINGLE-iOS/PINGLE-iOS/Network/Base/NetworkService.swift
  PINGLE-iOS/PINGLE-iOS/Network/Home/DTO/Request/HomePinListRequestQueryDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/Home/DTO/Response/HomePinListResponseDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/Home/Router/HomeTarget.swift
  PINGLE-iOS/PINGLE-iOS/Network/Home/Service/HomeService.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeMapView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeMapViewController.swift
Labels: Network, 채은

#69 Network [#67] 지도 핀 디테일 API 연결
  PINGLE-iOS/.swiftlint.yml
  PINGLE-iOS/PINGLE-iOS/Network/Home/Router/HomeTarget.swift
  PINGLE-iOS/PINGLE-iOS/Network/Home/Service/HomeService.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/Components/ParticipantButton.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeMapDetailView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeMapViewController.swift
Labels: Network, 채은

#72 Network [#68] 모임 참여 및 참여 취소 API 연결
  PINGLE-iOS/PINGLE-iOS/Network/Home/Router/HomeTarget.swift
  PINGLE-iOS/PINGLE-iOS/Network/Home/Service/HomeService.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeMapDetailView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeMapView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeMapViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Recommend/FixView.swift
Labels: Network, 채은

#73 Network [#63] 로그인 API 연결, 유저 정보 API 연결, 시작화면 분기처리
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Application/NetworkManager.swift
  PINGLE-iOS/PINGLE-iOS/Application/SceneDelegate.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/ImageLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgPINGLELogo.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgPINGLELogo.imageset/siglogo.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgPINGLELogo.imageset/siglogo@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgPINGLELogo.imageset/siglogo@3x.png
  PINGLE-iOS/PINGLE-iOS/Network/Base/HTTPHeaderFieldKey.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/KeychainHandler.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/NetworkService.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/TargetType.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/DTO/Request/LoginRequestBodyDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/DTO/l.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/Response/LoginResponseDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/Response/UserInfoResponseDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/Router/OnboardingTarget.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/Router/n.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/Service/OnboardingService.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/Service/m.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/LoginViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Splash/SplashViewController.swift
Labels: Network, 민수

#70 Feat[#59] final result view
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Literals/ImageLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicIntro.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicIntro.imageset/graphic.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicIntro.imageset/graphic@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicIntro.imageset/graphic@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicMulti.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicMulti.imageset/multi_graphic.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicMulti.imageset/multi_graphic@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicMulti.imageset/multi_graphic@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicOthers.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicOthers.imageset/cat_others_1000 1.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicOthers.imageset/cat_others_1000 1@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicOthers.imageset/cat_others_1000 1@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicPlay.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicPlay.imageset/play_graphic.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicPlay.imageset/play_graphic@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicPlay.imageset/play_graphic@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicStudy.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicStudy.imageset/study_graphic.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicStudy.imageset/study_graphic@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicStudy.imageset/study_graphic@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icUser.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icUser.imageset/all_ic_user.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icUser.imageset/all_ic_user@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icUser.imageset/all_ic_user@3x.png
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeMapView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ButtonCustomTest.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/View/CustomDatePickerView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/View/CustomTimePickerView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/View/FinalSummaryCardView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/DateSelectionViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/FinalResultViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/InsertOpenChatLinkViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/MakeMeetingGuideViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/MeetingIntroductionViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/PlaceSelectionViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/RecruitmentViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/SelectCategoryViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EntranceCompletedViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/TabBar/PINGLETabBarController.swift
Labels: Fix, Feat, 민지

#75 Fix [#74] 로그인, 온보딩 플로우 디자인 수정과 구글폼 링크 연결
  PINGLE-iOS/PINGLE-iOS/Global/Literals/ImageLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgApplogo.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgApplogo.imageset/applogo.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgApplogo.imageset/applogo@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgApplogo.imageset/applogo@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgCreateGraphic.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgCreateGraphic.imageset/create_graphic.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgCreateGraphic.imageset/create_graphic@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgCreateGraphic.imageset/create_graphic@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgGraphic1.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgGraphic1.imageset/graphic_1.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgGraphic1.imageset/graphic_1@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgGraphic1.imageset/graphic_1@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgSearchGraphic.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgSearchGraphic.imageset/search_graphic.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgSearchGraphic.imageset/search_graphic@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgSearchGraphic.imageset/search_graphic@3x.png
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EntranceCompletedViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/LoginViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/OnboardingViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/SearchOrganizationViewController.swift
Labels: Fix, 민수

#77 Network [#76] 단체 이름 검색 API 연결
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/DTO/Request/SearchOrganizationRequestQueryDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/Response/SearchOrganizationResponseDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/Router/OnboardingTarget.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/Service/OnboardingService.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/Cell/SearchCollectionViewCell.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/View/SearchOrganizationView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/SearchOrganizationViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/ViewController.swift
Labels: Network

#81 Network [#78] 기존 단체 입장 초대코드 화면 네트워크 구현
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Network/Base/HTTPHeaderFieldKey.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/DTO/Request/EnterInviteCodeRequestBodyDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/Response/EnterInviteCodeResponseDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/Response/OrganizationDetailResponseDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/Router/OnboardingTarget.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/Service/OnboardingService.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/Cell/SearchCollectionViewCell.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/View/OrganizationInfoView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EnterInviteCodeViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EntranceCompletedViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/LoginViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/SearchOrganizationViewController.swift
Labels: Network, 민수

#80 Feat[#79] singleton class result view
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/MeetingManager/MeetingManager.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/View/FinalSummaryCardView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/DateSelectionViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/FinalResultViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/InsertOpenChatLinkViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/MeetingIntroductionViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/PlaceSelectionViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/RecruitmentViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/SelectCategoryViewController.swift
Labels: Feat, 민지

#84 Refactor [#71] 홈 화면 collectionView로 리팩토링
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS.xcodeproj/xcshareddata/xcschemes/PINGLE-iOS.xcscheme
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/Cell/HomeDetailCollectionViewCell.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeDetailCancelPopUpView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeDetailPopUpView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeMapDetailView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeMapView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeMapViewController.swift
Labels: Refactor, 채은

#85 Network[#83] 장소 찾기 API 연결
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Network/Base/NetworkService.swift
  PINGLE-iOS/PINGLE-iOS/Network/Meeting/DTO/Request/SearchPlaceRequestQueryDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/Meeting/DTO/Response/SearchPlaceResponseDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/Meeting/Router/MeetingTarget.swift
  PINGLE-iOS/PINGLE-iOS/Network/Meeting/Service/MeetingService.swift
  PINGLE-iOS/PINGLE-iOS/Network/Meeting/q.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/Cell/PlaceSelectionCollectionViewCell.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/View/FinalSummaryCardView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/View/SearchPlaceView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/InsertOpenChatLinkViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/PlaceSelectionViewController.swift
Labels: Network, 민지

#89 Network[#86] make meeting API 연결
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Network/Base/HTTPHeaderFieldKey.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/TargetType.swift
  PINGLE-iOS/PINGLE-iOS/Network/Meeting/DTO/Request/MakeMeetingRequestBodyDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/Meeting/DTO/Request/SearchPlaceResponseDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/Meeting/Router/MeetingTarget.swift
  PINGLE-iOS/PINGLE-iOS/Network/Meeting/Service/MeetingService.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeMapViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/MeetingManager/MeetingManager.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/View/FinalSummaryCardView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/DateSelectionViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/FinalResultViewController.swift
Labels: Network, 민지

#91 Setting [#88] 릴리즈 준비
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/applogo.png
Labels: Setting, 채은

#97 Fix [#95] 대화 링크 데이터 전달 오류 해결
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/InsertOpenChatLinkViewController.swift
Labels: Fix, 민지

#96 Feat [#93] 로그인 온보딩 플로우 Pop Gesture 구현
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EnterInviteCodeViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/SearchOrganizationViewController.swift
Labels: Feat, 민수

#100 Feat[#99] make meeting label color
  PINGLE-iOS/PINGLE-iOS/Global/Extensions/UILabel+.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/MakeMeetingGuideViewController.swift
Labels: Feat, 민지

#101 Network [#82] 설정화면 로그아웃, 계정 탈퇴 API 연결
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Network/Base/HTTPHeaderFieldKey.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/KeychainHandler.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/NetworkService.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/PINGLERequestInterceptor.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/TargetType.swift
  PINGLE-iOS/PINGLE-iOS/Network/Profile/DTO/Response/AppleTokenResponse.swift
  PINGLE-iOS/PINGLE-iOS/Network/Profile/Router/ProfileTarget.swift
  PINGLE-iOS/PINGLE-iOS/Network/Profile/Service/ProfileService.swift
  PINGLE-iOS/PINGLE-iOS/Network/Profile/s.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EntranceCompletedViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/LoginViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/Component/OrganizationButton.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/View/SettingSelectView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/ViewController/SettingViewController.swift
Labels: Network, 민수

#103 Fix[#102] meeting post dto 오타 수정 및 도로명 주소 추가
  PINGLE-iOS/PINGLE-iOS/Network/Base/PINGLERequestInterceptor.swift
  PINGLE-iOS/PINGLE-iOS/Network/Meeting/DTO/Request/MakeMeetingRequestBodyDTO.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/MeetingManager/MeetingManager.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/FinalResultViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/PlaceSelectionViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/ViewController/SettingViewController.swift
Labels: Fix, 민지

#105 Fix [#90] 홈 화면 이슈 대응
  PINGLE-iOS/PINGLE-iOS/Application/SceneDelegate.swift
  PINGLE-iOS/PINGLE-iOS/Global/Extensions/CALayer+.swift
  PINGLE-iOS/PINGLE-iOS/Global/Extensions/UIView+.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/PINGLERequestInterceptor.swift
  PINGLE-iOS/PINGLE-iOS/Network/Home/DTO/Response/HomePinDetailResponseDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/Home/DTO/Response/HomePinListResponseDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/Home/Router/HomeTarget.swift
  PINGLE-iOS/PINGLE-iOS/Network/Home/Service/HomeService.swift
  PINGLE-iOS/PINGLE-iOS/Network/Meeting/Router/MeetingTarget.swift
  PINGLE-iOS/PINGLE-iOS/Network/Meeting/Service/MeetingService.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Base/BaseView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeMapDetailView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeMapView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeMapViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/InsertOpenChatLinkViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/MeetingIntroductionViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/RecruitmentViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EnterInviteCodeViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/LoginViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/SearchOrganizationViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/Component/OrganizationButton.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/View/SettingSelectView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/ViewController/SettingViewController.swift
Labels: Fix, 채은

#106 Fix [#104] interceptor 통신 재시도 구현
  PINGLE-iOS/PINGLE-iOS/Application/NetworkManager.swift
  PINGLE-iOS/PINGLE-iOS/Application/SceneDelegate.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/APIRequestLoader.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/PINGLERequestInterceptor.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/ViewController/SettingViewController.swift
Labels: Fix, 민수

#111 Fix [#109] 1차 QA 수정 사항 반영
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/Components/ParticipantButton.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeMapDetailView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeMapView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeMapViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/FinalResultViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/TabBar/PINGLETabBarController.swift
  PINGLE-iOS/PINGLE-iOS/Storyboard/ko.lproj/LaunchScreen.strings
Labels: Fix, 채은

#112 Fix[#108] 개최뷰 QA 요구사항 반영
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Components/PINGLECategoryButton.swift
  PINGLE-iOS/PINGLE-iOS/Global/Extensions/String+.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/ImageLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicIntro.imageset/graphic@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicIntro.imageset/graphic@3x.png
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ButtonCustomTest.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/Cell/PlaceSelectionCollectionViewCell.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/View/FinalSummaryCardView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/DateSelectionViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/FinalResultViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/InsertOpenChatLinkViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/MakeMeetingGuideViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/MeetingIntroductionViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/PlaceSelectionViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/RecruitmentViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/SelectCategoryViewController.swift
Labels: Fix, 민지

#110 Fix [#107] 온보딩, 설정 플로우 QA 반영
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Application/NetworkManager.swift
  PINGLE-iOS/PINGLE-iOS/Application/SceneDelegate.swift
  PINGLE-iOS/PINGLE-iOS/Global/Components/PINGLETextFieldView.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/HTTPHeaderFieldKey.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/PINGLERequestInterceptor.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/TargetType.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/Response/UserInfoResponseDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/Profile/Router/ProfileTarget.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/View/OrganizationInfoView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/View/SearchOrganizationView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EnterInviteCodeViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EntranceCompletedViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/LoginViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/OnboardingViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/SearchOrganizationViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/Component/OrganizationButton.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/Component/SettingSelectButton.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/View/AccountPopUpView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/View/SettingSelectView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/ViewController/MyOrganizationViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/ViewController/SettingViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Splash/SplashViewController.swift
Labels: Fix, 민수

#117 Fix [#115] 위치권한 info.plist 수정
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Info.plist
Labels: Fix, 채은

#118 Fix [#116] title 행간 이슈 조정
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/DateSelectionViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/FinalResultViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/InsertOpenChatLinkViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/MakeMeetingGuideViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/MeetingIntroductionViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/PlaceSelectionViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/RecruitmentViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/SelectCategoryViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EnterInviteCodeViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EntranceCompletedViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/LoginViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/OnboardingViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/SearchOrganizationViewController.swift
Labels: Fix, 민지

#122 Fix [#121] 분기처리의 역할을 SceneDelegate에서 SplashViewController로 이동
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Application/NetworkManager.swift
  PINGLE-iOS/PINGLE-iOS/Application/SceneDelegate.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/LoginViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Splash/SplashViewController.swift
Labels: Fix, 민수

#123 Feat[#120] 번개참여자뷰 UI 구현
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/Cell/ParticipantsCollectionViewCell.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/ParticipantsListView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/ParticipantsListViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/Model/SearchedPlaceModel.swift
Labels: Feat, 민지

#127 Fix [#126] 홈 지도 scroll move 수정
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeMapViewController.swift
Labels: Fix, 채은

#132 Feat [#119] 마이핑글 UI 구현
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Literals/ImageLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/btnMyPingleMore.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/btnMyPingleMore.imageset/my_ic_edit_frame.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/btnMyPingleMore.imageset/my_ic_edit_frame@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/btnMyPingleMore.imageset/my_ic_edit_frame@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icChat.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icChat.imageset/my_ic_chat.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icChat.imageset/my_ic_chat@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icChat.imageset/my_ic_chat@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icTrash.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icTrash.imageset/my_ic_trash__disable@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icTrash.imageset/my_ic_trash_disable.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icTrash.imageset/my_ic_trash_disable@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icTrashDisabled.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icTrashDisabled.imageset/my_ic_trash.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icTrashDisabled.imageset/my_ic_trash@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icTrashDisabled.imageset/my_ic_trash@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icUser 1.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icUser 1.imageset/all_ic_user.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icUser 1.imageset/all_ic_user@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icUser 1.imageset/all_ic_user@3x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgMyPingle.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgMyPingle.imageset/Group 1171276499.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgMyPingle.imageset/Group 1171276499@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgMyPingle.imageset/Group 1171276499@3x.png
  PINGLE-iOS/PINGLE-iOS/Network/MyPingle/MyPINGLEResponseDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/MyPingle/r.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeMapView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/Cell/MyPINGLECollectionViewCell.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/Components/MyPINGLESegmentControl.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/MyPINGLEViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/View/MoreView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/View/MyPINGLECardView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/ViewController/CompleteViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/ViewController/MyPINGLEViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/ViewController/SoonViewController.swift
Labels: Feat, 채은

#128 Fix [#125] navigationBarError 해결
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/AddPingleViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/ViewController/SettingViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/TabBar/PINGLETabBarController.swift
Labels: Fix, 민지

#130 Feat [#124] 단체장 탈퇴 시 경고 UI 구현
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Components/PINGLEWarningToastView.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/Model/SearchedModel.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/ViewController/SettingViewController.swift
Labels: Feat, 민수

#134 Fix [#129] 사용자를 찾을 수 없습니다 404 에러 시 로그인 화면으로 이동하게 했습니다.
  PINGLE-iOS/PINGLE-iOS/Network/Base/PINGLERequestInterceptor.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/Response/UserInfoResponseDTO.swift
Labels: Fix, 민수

#135 Network [#133] 마이 핑글 API 연결
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Extensions/UIView+.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/NetworkService.swift
  PINGLE-iOS/PINGLE-iOS/Network/Home/Router/HomeTarget.swift
  PINGLE-iOS/PINGLE-iOS/Network/Home/Service/HomeService.swift
  PINGLE-iOS/PINGLE-iOS/Network/MyPingle/DTO/Request/MyPINGLEListRequestQueryDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/MyPingle/DTO/Response/MyPINGLEResponseDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/MyPingle/MyPINGLEResponseDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/MyPingle/Router/MyPINGLETarget.swift
  PINGLE-iOS/PINGLE-iOS/Network/MyPingle/Service/MyPINGLEService.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/Cell/HomeDetailCollectionViewCell.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeMapDetailView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeMapViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/Cell/MyPINGLECollectionViewCell.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/View/MyPINGLECardView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/ViewController/CompleteViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/ViewController/MyPINGLEViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/ViewController/SoonViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/TabBar/PINGLETabBarController.swift
Labels: Network, 채은

#139 Feat [#136] 참여현황 홈 화면 및 마이핑글 연결
  PINGLE-iOS/PINGLE-iOS/Network/Base/PINGLERequestInterceptor.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/Cell/HomeDetailCollectionViewCell.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeMapDetailView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeMapViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/ParticipantsListViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/ViewController/CompleteViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/ViewController/MyPINGLEViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/ViewController/SoonViewController.swift
Labels: Feat, 채은

#140 Feat [#138] 강제 업데이트 로직 연결
  PINGLE-iOS/.swiftlint.yml
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Application/AppStoreCheck.swift
  PINGLE-iOS/PINGLE-iOS/Application/SceneDelegate.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Splash/SplashViewController.swift
Labels: Feat, 채은
