Repository TeamPINGLE/PINGLE-iOS, pull requests merged in 2024-03, with the labels that each got.

#179 Network, Fix [#177] 단체 개설 API 연결 및 그룹 정보 저장방식 변경
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Network/Base/KeychainHandler.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/TargetType.swift
  PINGLE-iOS/PINGLE-iOS/Network/Meeting/Service/MeetingService.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/DTO/Response/MakeTeamsResponseDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/Router/OnboardingTarget.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/Service/OnboardingService.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeListViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeMapViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/CheckOrganizationViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EnterInviteCodeViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EntranceCompletedViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/LoginViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/MakeCompletedViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/Component/OrganizationButton.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Recommend/ViewController/RecommendViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Splash/SplashViewController.swift
Labels: Fix, Network, 민수

#184 Feat [#180] 신규 단체 개설 초대코드 공유 UI, 공유하기 기능
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Components/PINGLETextFieldView.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icCopy.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icCopy.imageset/all_ic_copy.svg
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgGroupGraphic.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgGroupGraphic.imageset/group_graphic.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgGroupGraphic.imageset/group_graphic@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgGroupGraphic.imageset/group_graphic@3x.png
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/CheckOrganizationViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/MakeCompletedViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/ShareInviteCodeViewController.swift
Labels: Feat, 민수

#183 Fix [#181] ranking view 오류 해결
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Presentation/Recommend/View/NoRankingView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Recommend/View/RankingView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Recommend/ViewController/RecommendViewController.swift
Labels: Fix, Chore

#182 Feat [#154] 홈 리스트뷰 접히는 애니메이션 구현
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/Cell/HomeListCollectionViewCell.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/Model/HomeListData.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeListDetailView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeListViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeViewController.swift
Labels: Feat, 채은

#186 Feat [#185] 나의 단체 UI 작업
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgDefaltOwner.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgDefaltOwner.imageset/defalt_owner (1).svg
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgSelectedOwner.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/imgSelectedOwner.imageset/selected_owner (1).svg
  PINGLE-iOS/PINGLE-iOS/Network/Profile/DTO/Response/MyTeamsResponseDTO.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EnterOrganizationInfoViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/OnboardingViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/Cell/MyOrganizationCollectionViewCell.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/Component/OrganizationButton.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/View/AccountPopUpView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/View/CurrentOrganizationView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/View/ShareInviteCodePopUpView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/ViewController/MyOrganizationViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/ViewController/SettingViewController.swift
Labels: Feat, 민수

#192 Feat [#178] 검색뷰 구현, 분기처리 및 연결
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicSearch.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicSearch.imageset/etc_magglass_t 1.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicSearch.imageset/etc_magglass_t 1@2x.png
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/graphicSearch.imageset/etc_magglass_t 1@3x.png
  PINGLE-iOS/PINGLE-iOS/Network/Home/DTO/Request/HomePinListRequestQueryDTO.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/PINGLESearchView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeListViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeMapViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/SearchPINGLEViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/View/SearchPlaceView.swift
Labels: Fix, Feat, Network, 민지, Chore

#194 Fix [#189] 3차 스프린트 수정사항, Interceptor 수정, RequestLoader 수정
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/APIRequestLoader.swift
  PINGLE-iOS/PINGLE-iOS/Network/Base/PINGLERequestInterceptor.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/Cell/SearchCollectionViewCell.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EnterInviteCodeViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EnterOrganizationInfoViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/ManualViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/SearchOrganizationViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/ViewController/MyOrganizationViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/ViewController/SettingViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Splash/SplashViewController.swift
Labels: Fix, 민수

#190 Fix [#187] 리스트뷰 수정사항 반영
  PINGLE-iOS/PINGLE-iOS/Global/Components/PINGLEWarningToastView.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icInfoBlack.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icInfoBlack.imageset/all_ic_info_l.svg
  PINGLE-iOS/PINGLE-iOS/Network/Home/DTO/Response/HomePinDetailResponseDTO.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/Model/HomeListData.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeListDetailView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeMapDetailView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeListViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeMapViewController.swift
Labels: Fix, 채은

#197 Setting [#195] 앰플리튜드 기초 세팅
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Amplitude/AmplitudeEventType.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Amplitude/AmplitudeInstance.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Amplitude/AmplitudePropertyType.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Amplitude/AmplitudeUserProperty.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Config.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Info.plist
Labels: Setting, 채은

#199 Fix [#198] 기존 단체 가입 통신 response Code 변경에 따른 수정
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EnterInviteCodeViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/LoginViewController.swift
Labels: Fix, 민수, Chore

#203 Fix [#201] Interceptor retry 함수 수정
  PINGLE-iOS/PINGLE-iOS/Network/Base/PINGLERequestInterceptor.swift
Labels: Fix, 민수

#204 Feat [#202] General, 온보딩, 더보기 Amplitude 기능 구현
  PINGLE-iOS/PINGLE-iOS/Application/SceneDelegate.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Amplitude/AmplitudeEventType.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Amplitude/AmplitudePropertyType.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/CheckOrganizationViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EnterInviteCodeViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EnterOrganizationInfoViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EntranceCompletedViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/KeywordSelectionViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/LoginViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/MakeCompletedViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/OnboardingViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/SearchOrganizationViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/ShareInviteCodeViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/ViewController/MyOrganizationViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/ViewController/SettingViewController.swift
Labels: Feat, 민수

#206 Feat [#200] HomeMapViewController 검색결과 없을 시 UI 구현
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeListViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeMapViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/SearchPINGLEViewController.swift
Labels: Feat, 민지

#208 Feat [#196] 홈 지도, 리스트 화면 로직 점검 및 에러 처리
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeListViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeMapViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/SearchPINGLEViewController.swift
Labels: Fix, Feat, 채은

#210 Feat [#205] 홈 화면, 마이핑글 앰플리튜드 연결
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Amplitude/AmplitudeEventType.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Amplitude/AmplitudeInstance.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeListViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeMapViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/SearchPINGLEViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/Cell/MyPINGLECollectionViewCell.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/ViewController/CompleteViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/ViewController/MyPINGLEViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/ViewController/SoonViewController.swift
Labels: Feat, 채은

#214 Fix [#212] 자체 QA 오류사항 Fix
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Extensions/NotificationName+.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeListViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeMapViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/ViewController/SoonViewController.swift
Labels: Fix, 채은

#220 Fix [#218] 3차 전체 QA 사항 수정
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/Cell/HomeListCollectionViewCell.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeListDetailView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeListViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeMapViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/ViewController/SoonViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/ViewController/MyOrganizationViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/TabBar/PINGLETabBarController.swift
Labels: bug, Fix, 채은

#221 Fix [#217] 3차 전체 QA 수정사항 반영
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/View/OrganizationInfoView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EntranceCompletedViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/LoginViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/MakeCompletedViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/ManualViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/SearchOrganizationViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/Component/OrganizationButton.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/View/AccountPopUpView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/View/SettingSelectView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/ViewController/SettingViewController.swift
Labels: Fix, 민수

#222 Fix [#219] final qa fix
  PINGLE-iOS/PINGLE-iOS/Global/Extensions/NotificationName+.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/SearchPINGLEViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/ViewController/MyOrganizationViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Recommend/Cell/RankingCollectionViewCell.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Recommend/View/RankingView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Recommend/ViewController/RecommendViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/TabBar/PINGLETabBarController.swift
Labels: bug, Fix, 민지

#224 Fix [#223] 최종 오류 수정 (검색화면 진입 후 돌아왔을때 홈화면 search버튼 터치 안되는 이슈 해결)
  PINGLE-iOS/PINGLE-iOS/Presentation/TabBar/PINGLETabBarController.swift
Labels: bug, Fix, 민지

#225 Fix [#218] 3차 스프린트 추가 오류 사항 수정 (단체 변경 시 홈 화면 리셋)
  PINGLE-iOS/PINGLE-iOS/Global/Extensions/NotificationName+.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Profile/ViewController/MyOrganizationViewController.swift
Labels: Fix, 채은

#227 Fix [#226] 이메일입력 글자수 제한 해제
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EnterOrganizationInfoViewController.swift
Labels: Fix, 민수

#229 Fix [#228] 방문횟수 칩 크기 이슈 해결
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/FinalResultViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Recommend/Cell/RankingCollectionViewCell.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Recommend/View/RankingNumberView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Recommend/ViewController/RecommendViewController.swift
Labels: bug, Fix

#231 Fix [#230] 3차 스프린트 - 디자인 QA 수정 사항 반영
  PINGLE-iOS/PINGLE-iOS/Global/Extensions/UIView+.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icMyPingleArrow.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icMyPingleArrow.imageset/icMyPingleArrow.svg
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeMapView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeListViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/View/MyPINGLECardView.swift
Labels: Fix, 채은

#233 Fix [#232] iOS 16.4 미만 버전 UILabel 수정
  PINGLE-iOS/PINGLE-iOS/Global/Extensions/UILabel+.swift
Labels: Fix, 민수
