Repository TeamPINGLE/PINGLE-iOS, pull requests merged in 2024-02, with the labels that each got.

#146 Refactor [#144] 3차 스프린트 이전 멘토님 피드백 반영
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/Cell/HomeDetailCollectionViewCell.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/Components/ChipButton.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/Components/ParticipantButton.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeDetailCancelPopUpView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeDetailPopUpView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeMapDetailView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/View/HomeMapView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeListViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/HomeMapViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Home/ViewController/ParticipantViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/Cell/MyPINGLECollectionViewCell.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/Components/MyPINGLESegmentControl.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/View/MoreView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/View/MyPINGLECardView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/ViewController/CompleteViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/ViewController/MyPINGLEViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/MyPingle/ViewController/SoonViewController.swift
Labels: Refactor, 채은

#152 Chore [#150] 개발 서버 연결
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS.xcodeproj/xcshareddata/xcschemes/PINGLE-iOS.dev.xcscheme
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/applogo_dev.png
  PINGLE-iOS/PINGLE-iOS/Network/Home/Router/HomeTarget.swift
  PINGLE-iOS/PINGLE-iOS/Network/Meeting/Router/MeetingTarget.swift
  PINGLE-iOS/PINGLE-iOS/Network/MyPingle/Router/MyPINGLETarget.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/Router/OnboardingTarget.swift
  PINGLE-iOS/PINGLE-iOS/Network/Profile/Router/ProfileTarget.swift
  PINGLE-iOS/Podfile.lock
  PINGLE-iOS/Pods/Manifest.lock
  PINGLE-iOS/Pods/Pods.xcodeproj/project.pbxproj
  PINGLE-iOS/Pods/Target Support Files/Pods-PINGLE-iOS/Pods-PINGLE-iOS-frameworks-DEV-input-files.xcfilelist
  PINGLE-iOS/Pods/Target Support Files/Pods-PINGLE-iOS/Pods-PINGLE-iOS-frameworks-DEV-output-files.xcfilelist
  PINGLE-iOS/Pods/Target Support Files/Pods-PINGLE-iOS/Pods-PINGLE-iOS-frameworks.sh
Labels: 채은, Chore

#149 Refactor[#148] color asset key 관리
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/Color/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/Color/black.colorset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/Color/grayscaleG01.colorset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/Color/grayscaleG02.colorset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/Color/grayscaleG03.colorset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/Color/grayscaleG04.colorset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/Color/grayscaleG05.colorset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/Color/grayscaleG06.colorset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/Color/grayscaleG07.colorset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/Color/grayscaleG08.colorset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/Color/grayscaleG09.colorset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/Color/grayscaleG10.colorset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/Color/grayscaleG11.colorset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/Color/mainPingleGreen.colorset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/Color/subPingleOrange.colorset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/Color/subPingleYellow.colorset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/Color/systemRedAlert.colorset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/Color/white.colorset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Color.swift
Labels: Refactor

#162 Feat [#160] 신규 단체명 입력 및 대표 이메일 뷰 UI 구현
  PINGLE-iOS/PINGLE-iOS/Global/Components/PINGLETextFieldView.swift
  PINGLE-iOS/PINGLE-iOS/Global/Components/PINGLEWarningToastView.swift
  PINGLE-iOS/PINGLE-iOS/Global/Extensions/String+.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icCheckGray.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icCheckGray.imageset/setting_ic_check_gray.svg
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icInfoBig.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/icInfoBig.imageset/all_ic_info_l.svg
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EnterOrganizationInfoViewController.swift
Labels: Feat, 민수

#164 Network [#163] 단체 이름 중복 검사 API 연결
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/DTO/Request/CheckNameRequestParameterDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/DTO/Response/CheckNameResponseDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/Router/OnboardingTarget.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/Service/OnboardingService.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EnterOrganizationInfoViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/KeywordSelectionViewController.swift
Labels: Feat, Network, 민수

#169 Network [#168] 키워드 API 연결
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/DTO/Response/KeywordResponseDTO.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/Router/OnboardingTarget.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/Service/OnboardingService.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/Cell/KeywordColletionViewCell.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/KeywordSelectionViewController.swift
Labels: Feat, Network, 민수

#173 Feat [#171] 개최뷰 검색뷰 clear 버튼 추가
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/btnClear.imageset/Contents.json
  PINGLE-iOS/PINGLE-iOS/Global/Resources/Assets.xcassets/btnClear.imageset/clear.svg
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/View/SearchPlaceView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Meeting/ViewController/PlaceSelectionViewController.swift
Labels: Fix, Feat

#176 Feat [#170] 단체 개설 정보 확인 뷰 UI 작업
  PINGLE-iOS/PINGLE-iOS.xcodeproj/project.pbxproj
  PINGLE-iOS/PINGLE-iOS/Global/Extensions/LeftAlignedCollectionViewFlowLayout.swift
  PINGLE-iOS/PINGLE-iOS/Global/Literals/StringLiterals.swift
  PINGLE-iOS/PINGLE-iOS/Network/Onboarding/DTO/Request/MakeTeamsRequestBodyDTO.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/View/OrganizationInfoView.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/CheckOrganizationViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EnterInviteCodeViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/EnterOrganizationInfoViewController.swift
  PINGLE-iOS/PINGLE-iOS/Presentation/Onboarding/ViewController/KeywordSelectionViewController.swift
Labels: Feat, 민수
